### ISSUE TITLE
[OT] Netlify

### ISSUE THREAD

**Issue by KatelynRankin** [janheinrichmerker/website#3]
Another alternative to using your awesome bash scripts ```build.sh``` and ```refresh-portfolio.sh``` might be @netlify ([homepage](https://www.netlify.com/)). I think you should stay with your bash scripts for now but maybe [Netlify](https://www.netlify.com/) might be an option for another project or the project of a visitor of your repo.

**Comment by janheinrichmerker** [comment]
Yeah, Netlify is great for that, and I have even considered it while developing the bash script, but I'll try to keep the control over my web server as long as I can. Maybe in future I'm going to link my web server to a GitHub webhook.

**Comment by janheinrichmerker** [comment]
In the meantime, we got GitHub Actions and I decided to put the shell scripts into a CI and CD workflow.
This issue should be fixed by #5.
